### ISSUE TITLE
Addon repositories?

### ISSUE THREAD

**Issue by lkraav** [rubengc/GamiPress#1]
Hi. How come none of the addon repositories seem to be available on GH? We need to perform an audit of at least the Sensei and BadgeOS code and history to be safe of the migration processes quality. Is the history available somewhere else?

**Comment by rubengc** [comment]
Hi @lkraav 

WordPress.org is a repository (SVN) for WordPress plugins so we track everything on WordPress

On any plugin, check the development tab where you find instructions and links to access to the repository through web

We opened this repository with future plans to use it a support platform but finally support is taken through our website

Best regards

**Comment by rubengc** [comment]
Hi @lkraav

Internally we use GitLab and other tools to keep the team in contact, WordPress.org repositories are just the public way to show everyone what we are doing internally

We wanted to use Github for GamiPress and free add-ons in order to keep an active communication with the contributors, but, our 99.9% of tickets are for non-developers, so why request them to create an account on Github when they already has one on WordPress.org or on gamipress.com

Best regards

**Comment by lkraav** [comment]
Thanks. Let's say we move forward with our migration to GP and look to adopt it as our core platform component. Is there a path to becoming a git-contributor on your GitLab? Vendors also often have a #friends Slack/Mattermost/other channel for gaining additional dev insight before filing issues. Because sometimes the understanding of (large) outside systems needs to be tuned through discussion, until becomes ready to file an accurate issue.

**Comment by rubengc** [comment]
Hi @lkraav

On Gitlab there are just our paid add-ons repositories

If you want to contribute to GamiPress, simply open any pull request you want here

For the rest of integrations or free, simply request what you are looking for or whatever you need

Best regards
