### ISSUE TITLE
gamipress_send_email a bit more customization

### ISSUE THREAD

**Issue by alijiwani** [rubengc/GamiPress#16]
hello,
thanks for the last request where email attachments.

Within the `gamipress_send_email` function is there a way that i can hook into it using the achievement id?
Or maybe i need to look into `gamipress_maybe_send_email_to_user`?

I am looking to modify the email contents based on the achievement type and their id.

My final aim is to send users a set of instructions and images based on their badge.

Thanks for the plugin and support

**Comment by rubengc** [comment]
Hi @alijiwani 

I am so sorry but we do not offer support for customizations like that since our main focus is the development and maintenance of GamiPress, AutomatorWP and all official add-ons. 

Anyway, any WordPress custom development agency or freelancer can handle it for you.

If you do not know one, we recommend checking our list of trusted experts that can estimate any type of job for you here:
https://gamipress.com/customizations/

Best regards

**Comment by alijiwani** [comment]
Thanks.
A question though, for `gamipress_maybe_send_email_to_user` on #830 or #880 or anywhere where `gamipress_send_email` is called, can it be wrapped under apply_filter so that if any devs want to hook into it they could and maybe pass more variables if/when needed because at this time it doesnt look feasible unless you change the core?

Example #830 of `gamipress_maybe_send_email_to_user` where `gamipress_send_email` is being called adding the `$achievement_id` or `$gamipress_email_template_args` would have allowed the devs to modify and customize the email as needed.

This is just a suggestion and really appreciate the super fast response.

**Comment by rubengc** [comment]
Hi @alijiwani 

`$gamipress_email_template_args` is a global var, it means that can be accessed in the following hooks executed.

Hope it helps!

**Comment by alijiwani** [comment]
That resolved my problem, thankyou so very much
