### ISSUE TITLE
Warning: call_user_func_

### ISSUE THREAD

**Issue by KaDim2515** [rubengc/GamiPress#21]
Help solve the problem! Worth the BuddyBoss platform.
I'm trying to connect gamipress , but I get this error: **Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'gamipress_achievements' not found or invalid function name in.....

![ScreenShot_20221023022758](https://user-images.githubusercontent.com/100047427/197363066-4b3175b5-bdd6-4b93-a72c-c6a6c669f251.png)
**
![ScreenShot_20221023023036](https://user-images.githubusercontent.com/100047427/197363138-2cc382ec-28af-4fa4-8acb-55fe29752d69.png)

**Comment by rubengc** [comment]
Hi there!

Your issue seems that a plugin is revealing our hidden achievements menu (probably a custom dashboard menu plugin)

GamiPress has a hidden achievements menu (also for ranks) and this menu is only displayed when you have at least 1 achievement type configured (also this menu will display options for all achievements types defined)

So the solutions here are (follow 1 of these options):
1 - Register at least an achievement type in GamiPress > Achievement Types > Add new
2 - Do not access to the "Achievements" menu if you do not have any achievement type or you do not have plans to use achievements (also from your custom dashboard menu plugin, you could hide this menu if you do not have plans to use achievements)
3 - Deactivate the custom dashboard menu plugin to prevent to reveal that hidden menu

Hope it helps! 😁

**Comment by KaDim2515** [comment]
Но мне нужны достижения =DDD а никаких пользовательских меню у меня нет. Только стоковое от WP

**Comment by KaDim2515** [comment]
вопрос не решён :(

**Comment by rubengc** [comment]
You need to create first an achievement type as explained here: https://gamipress.com/docs/tutorials/creating-an-achievement-type/

and please write your comments in english since in this way any one can understand them without need a translator
